### PR TITLE
lvgl: Rename kconfig symbols from LVGL to LV

### LINKED ISSUE #191: Update Kconfig symbol names to start with LV instead of LVGL
See [here](https://github.com/zephyrproject-rtos/zephyr/issues/27772).

### PR DESCRIPTION
**Pull request by C47D**
Closes #191 

This is part of the work to include the Kconfig file into the main LVGL repo.

### CODE REVIEW

**Comment by embeddedt** [comment]
Looks good. Unfortunately I think it will break existing configs that are using the LVGL names. I'm not sure if anything can be done about that.

**Comment by C47D** [comment]
Do you mean configuration of the drivers found in this repo? If so grepped for `CONFIG_LVGL_` and found nothing.

**Review by kisvegabor — APPROVED** [review]
Looks good!

**Comment by C47D** [comment]
Is your last comment addressed with the last commit @embeddedt?

**Review by embeddedt — APPROVED** [review]
GitHub seems to require me to leave a message when approving changes now. :slightly_smiling_face: Looks good to me.

**Pull request merged**
