### PR TITLE
[LVGL] Refactor Kconfig and lv_conf.h

### PR DESCRIPTION
**Pull request by C47D**
Continuation from #216

### CODE REVIEW

**Comment by C47D** [comment]
@embeddedt I'm thinking on doing something similar to cde3024 for boolean symbols, what do you think?

**Comment by embeddedt** [comment]
That looks like it would work.

**Comment by C47D** [comment]
Ok, I will keep going and mark the PR as ready for review when I'm done.

**Review by kisvegabor — APPROVED** [review]
Looks good to me as well!

**Comment by C47D** [comment]
I think I'm almost done, the bulk of the remaining work is on the fonts section of the `lv_conf.h` file. If the `CONFIG_LV_FONT_MONTSERRAT` symbol is not defined the font will be not enabled by the `lv_conf_internal.h`. So I think this is the expected behaviour.

`lv_conf_internal.h`
```c
#ifndef LV_FONT_MONTSERRAT_8
#  ifdef CONFIG_LV_FONT_MONTSERRAT_8
#    define LV_FONT_MONTSERRAT_8 CONFIG_LV_FONT_MONTSERRAT_8
#  else
#    define  LV_FONT_MONTSERRAT_8     0
#  endif
#endif
```

Other "issue" is how the fonts are setted in `lv_conf_ìnternal.h`:
```c
#ifndef LV_THEME_DEFAULT_FONT_NORMAL
#  ifdef CONFIG_LV_THEME_DEFAULT_FONT_NORMAL
#    define LV_THEME_DEFAULT_FONT_NORMAL CONFIG_LV_THEME_DEFAULT_FONT_NORMAL
#  else
#    define  LV_THEME_DEFAULT_FONT_NORMAL        &lv_font_montserrat_14
#  endif
#endif
```

`CONFIG_LV_THEME_DEFAULT_FONT_NORMAL` can´t be set to be something like `&lv_font_montserrat_14`, that is why we used something like this in the current `lv_conf.h`
```c
#if defined CONFIG_LV_FONT_DEFAULT_NORMAL_MONTSERRAT_12
#define LV_THEME_DEFAULT_FONT_NORMAL         &lv_font_montserrat_12
#elif defined CONFIG_LV_FONT_DEFAULT_NORMAL_MONTSERRAT_14
#define LV_THEME_DEFAULT_FONT_NORMAL         &lv_font_montserrat_14
#elif defined CONFIG_LV_FONT_DEFAULT_NORMAL_MONTSERRAT_16
#define LV_THEME_DEFAULT_FONT_NORMAL         &lv_font_montserrat_16
#elif defined CONFIG_LV_FONT_DEFAULT_NORMAL_MONTSERRAT_18
#define LV_THEME_DEFAULT_FONT_NORMAL         &lv_font_montserrat_18
#elif defined CONFIG_LV_FONT_DEFAULT_NORMAL_MONTSERRAT_20
/* same for all fonts */
```

So I think we should update the `lv_conf_internal.h` file with that approach.

Any opinions @embeddedt @kisvegabor ?

**Comment by C47D** [comment]
Also I think we can split the Kconfig file into several (one for fonts, other for objects, etc.) using the `source` keyword (See [The Kernel Configuration and Build Process](https://www.linuxjournal.com/article/6568)).

**Comment by kisvegabor** [comment]
> #if defined CONFIG_LV_FONT_DEFAULT_NORMAL_MONTSERRAT_12
#define LV_THEME_DEFAULT_FONT_NORMAL         &lv_font_montserrat_12
#elif defined CONFIG_LV_FONT_DEFAULT_NORMAL_MONTSERRAT_14
#define LV_THEME_DEFAULT_FONT_NORMAL         &lv_font_montserrat_14
#elif defined CONFIG_LV_FONT_DEFAULT_NORMAL_MONTSERRAT_16
#define LV_THEME_DEFAULT_FONT_NORMAL         &lv_font_montserrat_16
#elif defined CONFIG_LV_FONT_DEFAULT_NORMAL_MONTSERRAT_18
#define LV_THEME_DEFAULT_FONT_NORMAL         &lv_font_montserrat_18
#elif defined CONFIG_LV_FONT_DEFAULT_NORMAL_MONTSERRAT_20
/* same for all fonts */

It seems working but now `lv_conf_internal.h` is simply generated from `lv_conf_templ.h`. With this, we need to add some hardcoded logic to replace some parts.

I've opened a question about it in [Stackoverflow](https://stackoverflow.com/questions/64367658/select-a-variables-name-in-kconfig).

**Comment by C47D** [comment]
I was able to load the Kconfig.fonts file into the main lvgl Kconfig file, so now we can split the different lvgl Kconfig menus into separated files, this would allow it to become more readable. Let me know what do you think, if you like that idea I will create a Kconfig file for the themes, log, debug and text settings and widgets.

**Comment by C47D** [comment]
I think I'm wrong about the boolean configuration options because in the particular version of lvgl used in this project the `lv_conf_internal` doesn't handle undefined `CONFIG_x` options, that's why I have to always have the `CONFIG_x` symbols defined.

On the current lv_conf_internal (lvgl master) the non defined CONFIG_x options defaults to not enabled configurations.

**Comment by kisvegabor** [comment]
> Let me know what do you think, if you like that idea I will create a Kconfig file for the themes, log, debug and text settings and widgets.

I like the idea in general. However, I'm afraid if we will have ~5-10 Kconfig files in the root folder it will look messy. IS there a way to put the Kconfig files into a folder?

> On the current lv_conf_internal (lvgl master) the non defined CONFIG_x options defaults to not enabled configurations.

Something like this would work better?
```c
#ifndef LV_ANTIALIAS  /*Only if it's defined somewhere...*/
/*If using with Kconfig*/
#  if LV_KCONFIG_ENV
#    ifdef CONFIG_LV_ANTIALIAS
#      define LV_ANTIALIAS   CONFIG_LV_ANTIALIAS
#    else
#      define LV_ANTIALIAS   0
#    endif
/*If not using Kconfig*/
#  else
#    define LV_ANTIALIAS   0
#  endif
#endif
```

Non-bool values are always defined, right?

**Comment by C47D** [comment]
> I like the idea in general. However, I'm afraid if we will have ~5-10 Kconfig files in the root folder it will look messy. IS there a way to put the Kconfig files into a folder?

That's also true, I don't think is possible to put the Kconfig in other folder and make it work with both Zephyr and Esp-idf.

And about handling CONFIG_x symbols the current approach is fine.

I will open another PR and close this one.

**Comment by embeddedt** [comment]
I think the `source` directive supports relative folder names, however, I don't know if they are interpreted relative to the `Kconfig` file's location, or to the current working directory.

**Comment by C47D** [comment]
It does, I'm currently using a relative path, but taking the build directory of the esp-idf project. The Zephyr directory layout is different.

The rsource extension supports relative paths but starting from the Kconfig, so you only have to add `rsource Kconfig.fonts` and such.
The rsource is an extension by the Kconfiglib library that esp-idf uses to handle Kconfig files.

**Comment by kisvegabor** [comment]
>  I'm currently using a relative path, but taking the build directory of the esp-idf project. The Zephyr directory layout is different.

If we need to hardcore project specific paths, I think, it's better to stick with monolithic Kconfig.

**Comment by C47D** [comment]
> If we need to hardcore project specific paths, I think, it's better to stick with monolithic Kconfig.

I agree, in #219 I've keept the monolithic Kconfig and added some missing options, let's continue over there.

**Pull request closed without merging**
