### PR TITLE
[WIP] Update readme

### PR DESCRIPTION
**Pull request by C47D**
Update instructions on how to use `LVGL`, `lvgl_esp32_drivers`, moved part of the README into the lvgl_esp32_drivers [repo](https://github.com/lvgl/lvgl_esp32_drivers/pull/12).

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]
Loks good!

**Comment by C47D** [comment]
@kisvegabor I've removed some old information, later can you send a PR to update the images on the readme? my photos sucks :smile: 
Let me know if I should merge this.

**Comment by kisvegabor** [comment]
Unfortunately, I don't really have boards for ESP just a WROOM module and a TFT with ILI9341.
I'll ask our graphics designer to try to improve the current images.
If it doesn't work, I  have some friends who can shot some photos.

**Comment by C47D** [comment]
Hi,
Me neither, maybe I will buy one later this month.

**Pull request merged**
