### PR TITLE
Fixed compile errors

### PR DESCRIPTION
**Pull request by an-erd**
- Added missing '"'.

- Added closing #endif. 
Please check that the logic is ok with this #endif.

### CODE REVIEW

**Comment by C47D** [comment]
Should I test this instead of #150?

**Comment by an-erd** [comment]
I used this path [https://github.com/lvgl/lv_port_esp32/blob/master/components/lvgl/lv_conf.h](https://github.com/lvgl/lv_port_esp32/blob/master/components/lvgl/lv_conf.h) on the current master. 

The lvgl is submodule commit #4f3dac6. 

An the file above does have the lines shown, lines 510, 551 and 569 and is included in a commit 3 days ago, see [here](https://github.com/lvgl/lv_port_esp32/commit/51c5e02be37577048acef849903613e8505e1ff0). 

Do you want me to change the PR?

**Comment by C47D** [comment]
I've created a new branch with your changes from #150 and #151 https://github.com/lvgl/lv_port_esp32/tree/st7735s_update

I think it does include all your changes, does it work for you?

**Comment by an-erd** [comment]
Yes, works as expected. I'll delete #150 and #151.

**Comment by C47D** [comment]
Thanks for the confirmation, I will merge as soon as I get a chance.

**Pull request closed without merging**
