### PR TITLE
Added st7796s driver

### PR DESCRIPTION
**Pull request by damianog**
Added st7796s driver for WirelessTag  device WT32-SC01

image

image

### CODE REVIEW

**Comment by damianog** [comment]
Hi @C47D could you have a look? I copied from ili9481 and merged some changes from an old fork from https://github.com/wireless-tag-com/lv_port_esp32

**Comment by damianog** [comment]
@C47D Is there a way to setup also the touch panel with predefined display settings? The WT32-SC01 use FT6x06 with PIN 18 and PIN 19 for SDA and SCL

**Comment by C47D** [comment]
Hi @damianog,

Maybe you can try to do something like this in the `lvgl_touch` Kconfig file:

```diff
diff --git a/components/lvgl_esp32_drivers/lvgl_touch/Kconfig b/components/lvgl_esp32_drivers/lvgl_touch/Kconfig
index 1957771..93c6c15 100644
--- a/components/lvgl_esp32_drivers/lvgl_touch/Kconfig
+++ b/components/lvgl_esp32_drivers/lvgl_touch/Kconfig
@@ -186,6 +186,7 @@ menu "LVGL Touch controller"
             int
             prompt "GPIO for SDA (I2C)"
         range 0 39
+            default 18 if LV_PREDEFINED_DISPLAY_WT32_SC01
             default 21
             help
             Configure the I2C touchpanel SDA pin here.
@@ -193,6 +194,7 @@ menu "LVGL Touch controller"
         config LV_TOUCH_I2C_SCL
             int "GPIO for clock signal SCL (I2C)"
         range 0 39
+            default 19 if LV_PREDEFINED_DISPLAY_WT32_SC01
             default 22
             help
             Configure the I2C touchpanel SCL pin here.
```

**Comment by C47D** [comment]
@damianog did it worked as expected?

If not you can also do something like this:
```
menu "Touchpanel (FT6X06) Pin Assignments"
        depends on LV_TOUCH_CONTROLLER_FT6X06

        config LV_TOUCH_I2C_SDA
            int "GPIO for SDA (I2C)" if !LV_PREDEFINED_DISPLAY_WT32_SC01
        range 0 39
            default 18 if LV_PREDEFINED_DISPLAY_WT32_SC01
            default 21
            help
            Configure the I2C touchpanel SDA pin here.

        config LV_TOUCH_I2C_SCL
            int "GPIO for clock signal SCL (I2C)" if !LV_PREDEFINED_DISPLAY_WT32_SC01
        range 0 39
            default 19 if LV_PREDEFINED_DISPLAY_WT32_SC01
            default 22
            help
            Configure the I2C touchpanel SCL pin here.
    endmenu
```

This way the prompts for `LV_TOUCH_I2C_SDA` and `LV_TOUCH_I2C_SCL` are not displayed (you don't need them in preconfigured board pinouts) and the `default 19 if LV_PREDEFINED_DISPLAY_WT32_SC01` and `default 18 if LV_PREDEFINED_DISPLAY_WT32_SC01` are used.

I don't remember how to hide the `"Touchpanel (FT6X06) Pin Assignments"` menu tho.

**Comment by damianog** [comment]
@C47D yes it worked, I committed the changes, unfortunately I did not managed to select the type of touch panel too.
I hided as you suggested the pin change with a different approach
```
    menu "Touchpanel (FT6X06) Pin Assignments"
        depends on LV_TOUCH_CONTROLLER_FT6X06
        visible if !LV_PREDEFINED_DISPLAY_WT32_SC01
``` 
as explained by  https://docs.zephyrproject.org/1.14.0/guides/kconfig/index.html#visible-if-conditions

**Comment by C47D** [comment]
I haven't used the touch Kconfig for a while, and I'm not in my development machine, can you try something like this:

```
    choice
	prompt "Select a touch panel controller model."
        visible if !LV_PREDEFINED_DISPLAY_WT32_SC01
        default LV_TOUCH_CONTROLLER_FT6X06 IF LV_PREDEFINED_DISPLAY_WT32_SC01
	default LV_TOUCH_CONTROLLER_NONE
	help
	    Select the controller for your touch panel.

	config LV_TOUCH_CONTROLLER_NONE
	    bool "None"
	config LV_TOUCH_CONTROLLER_XPT2046
            select LV_TOUCH_DRIVER_PROTOCOL_SPI
            bool "XPT2046"
	config LV_TOUCH_CONTROLLER_FT6X06
            select LV_TOUCH_DRIVER_PROTOCOL_I2C
            bool "FT6X06"
        config LV_TOUCH_CONTROLLER_STMPE610
            select LV_TOUCH_DRIVER_PROTOCOL_SPI
            bool "STMPE610"
        config LV_TOUCH_CONTROLLER_ADCRAW
            select LV_TOUCH_DRIVER_ADC
            bool "ADCRAW"
        config LV_TOUCH_CONTROLLER_FT81X
            select LV_TOUCH_DRIVER_PROTOCOL_SPI
            bool "FT81X"
        config LV_TOUCH_CONTROLLER_RA8875
            select LV_TOUCH_DRIVER_DISPLAY
            bool "RA8875"
    endchoice
```

**Comment by damianog** [comment]
> I haven't used the touch Kconfig for a while, and I'm not in my development machine, can you try something like this:
> 
> ```
>     choice
> 	prompt "Select a touch panel controller model."
>         visible if LV_PREDEFINED_DISPLAY_NONE
>         default LV_TOUCH_CONTROLLER_FT6X06 if LV_PREDEFINED_DISPLAY_WT32_SC01
> 	default LV_TOUCH_CONTROLLER_NONE
> 	help
> 	    Select the controller for your touch panel.
> 
> 	config LV_TOUCH_CONTROLLER_NONE
> 	    bool "None"
> 	config LV_TOUCH_CONTROLLER_XPT2046
>             select LV_TOUCH_DRIVER_PROTOCOL_SPI
>             bool "XPT2046"
> 	config LV_TOUCH_CONTROLLER_FT6X06
>             select LV_TOUCH_DRIVER_PROTOCOL_I2C
>             bool "FT6X06"
>         config LV_TOUCH_CONTROLLER_STMPE610
>             select LV_TOUCH_DRIVER_PROTOCOL_SPI
>             bool "STMPE610"
>         config LV_TOUCH_CONTROLLER_ADCRAW
>             select LV_TOUCH_DRIVER_ADC
>             bool "ADCRAW"
>         config LV_TOUCH_CONTROLLER_FT81X
>             select LV_TOUCH_DRIVER_PROTOCOL_SPI
>             bool "FT81X"
>         config LV_TOUCH_CONTROLLER_RA8875
>             select LV_TOUCH_DRIVER_DISPLAY
>             bool "RA8875"
>     endchoice
> ```

the visible condition must be near the menu branch otherwise it cause compilation error.
I tried everything but choice is not updated by the conditional default.
I think we are in this situation: https://github.com/zephyrproject-rtos/zephyr/issues/6948

**Comment by C47D** [comment]
I will try to solve it later today.

**Comment by C47D** [comment]
Hi @damianog I've added most of this PR into [here](https://github.com/lvgl/lvgl_esp32_drivers/tree/feature/add_st7796s). We've recently moved all the drivers over that repository as we plan to work on them in the next months.

I will add the fix for the touch Kconfig in the coming days.

**Comment by damianog** [comment]
@C47D good, so I proceed to close this PR.

**Comment by C47D** [comment]
@damianog let me know if you find any issues.

**Pull request closed without merging**
