### PR TITLE
Esp32 port updated to v7

### PR DESCRIPTION
**Pull request by barbiani**
Update the esp32 port to v7
Added adc touch driver

### CODE REVIEW

**Comment by C47D** [comment]
Thanks for the PR.

I think this should be separated into two different PRs, one for the adc reader and another to update lvgl and lv_examples submodules to v7.

The adc PR can be merged into the master branch of this repo and the v7 update can be merged into a dev branch, because both submodules are still release candidates. 

What do you think?

**Comment by barbiani** [comment]
I do not have a commit with the v7 upgrade alone.

**Comment by barbiani** [comment]
The adc touch addition changed a kconfig file that was modified to work with v7.

I do not know how to break the big commit now.

**Comment by kisvegabor** [comment]
What about merging into `dev-7.0`? This way ADC driver can be added to `master` when v7.0 is released.

**Comment by C47D** [comment]
@kisvegabor I will create that branch soon, I'm cleaning the code a little to add drivers more easily. As @barbiani said the adc code works on v7

**Comment by embeddedt** [comment]
What's the difference between this and #110? Is one waiting to be merged with the other?

**Comment by C47D** [comment]
#110 includes commits from master fixing some bugs, code cleanup, etc. I don't know how many commits #110 is ahead of this PR. AFAIK 110 already include changes from here.

**Comment by C47D** [comment]
#110 was merged, it took some changes made here, thanks @barbiani. Further improvements can be discussed in new issues or PRs.

**Pull request closed without merging**
